# Increase memory available to Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod properties
version=1.0.11.1+26.2
group=pw.lakuna
id=elytra_trinket
modrinth_id=wk57PrDM

# Dependencies
fabric_api_version=0.152.1+26.2
trinkets_api_version=4.1.0-beta.1+26.2
java_version=25
