# Increase memory available to Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric properties
minecraft_version=26.1.2
loader_version=0.18.4
loom_version=1.16-SNAPSHOT

# Mod properties
version=1.0.11
group=pw.lakuna
id=elytra_trinket
modrinth_id=wk57PrDM

# Dependencies
fabric_api_version=0.147.0+26.1.2
trinkets_api_version=4.0.0-alpha.9+26.1
java_version=25
